services:
  - docker

# branches:
#   only:
#     - main

script: 
  - echo "Building Docker container..."
  - docker-compose up -d #detach mode 
  - echo "Waiting for Docker container to finish setting up..."
  - ./db/waitForContainerSetup.sh
  - echo "Connecting to app's docker..."
  - docker exec -it lanachanllenge_app_1 /bin/bash
  - echo "Running tests..."
  - python3 -m unittest tests.tests # run tests