services:
  - docker

# branches:
#   only:
#     - main

script: 
  - echo "Building Docker container..."
  - docker-compose up -d #detach mode 
  - echo "Waiting for Docker container to finish setting up..."
  - ./db/waitForContainerSetup.sh
  - echo "Connecting to app's docker and running tests..."
  - docker exec -it lanachallenge_app sh -c "python3 -m unittest tests.tests"