language: python
python:
  - "3.8.5"

services:
  - docker

# branches:
#   only:
#     - main

before_script: pip install docker-compose

script: 
  - docker-compose build
  - docker inspect lanachallenge_app | grep IPAddress
  - docker inspect lanachallenge_postgres | grep IPAddress
  - docker-compose run app sh -c "python3 -m unittest tests.tests"