language: python
python:
  - "3.8.5"

services:
  - docker

branches:
  only:
    - main

before_script:
  - python --version  
  - pip install -U pip
install:
  - pip install -r requirements.txt
script: 
  - docker-compose up -d #detach mode 
  - python -m unittest tests.tests # run tests