language: python
python:
  - "3.8.5"

services:
  - docker

# branches:
#   only:
#     - main

before_script: pip install docker-compose

script: 
  - docker-compose run app sh -c "python3 -m unittest tests.tests"