language: python
python:
  - "3.8.5"

services:
  - docker

# branches:
#   only:
#     - main

before_script: pip install docker-compose

script: 
  - docker network create --driver=bridge --subnet=172.21.0.0/24 lanachallenge_network
  - docker-compose run app sh -c "python3 -m unittest tests.tests"