# Generated by Django 2.1.15 on 2021-06-28 16:36

from django.db import migrations


def load_products(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    product_to_save = Product(code='PEN', name='Lana Pen', price=5.00)
    product_to_save.save()
    product_to_save = Product(code='TSHIRT', name='Lana TShirt', price=20.00)
    product_to_save.save()
    product_to_save = Product(code='MUG', name='Lana Coffee Mug', price=7.50)
    product_to_save.save()


def delete_products(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    Product.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(load_products, delete_products),
    ]
